name: Docker test from docker-compose
on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "dev" ]

jobs:

  test:  
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build docker images
      run: docker-compose build

